"""convert secteur enum columns to managed referentiel strings

Revision ID: 5b1bbe1965c4
Revises: 96f28269c142
Create Date: 2026-08-10 19:30:29.164557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b1bbe1965c4'
down_revision: Union[str, Sequence[str], None] = '96f28269c142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boutique_secteurs', 'secteur',
               existing_type=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('fournisseurs', 'secteur',
               existing_type=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('produits', 'secteur',
               existing_type=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('promotions', 'secteur',
               existing_type=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               type_=sa.String(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'secteur',
               existing_type=sa.String(length=60),
               type_=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               existing_nullable=True)
    op.alter_column('produits', 'secteur',
               existing_type=sa.String(length=60),
               type_=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               existing_nullable=False)
    op.alter_column('fournisseurs', 'secteur',
               existing_type=sa.String(length=60),
               type_=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               existing_nullable=False)
    op.alter_column('boutique_secteurs', 'secteur',
               existing_type=sa.String(length=60),
               type_=mysql.ENUM('habillement', 'alimentation_generale', 'electronique_electromenager'),
               existing_nullable=False)
    # ### end Alembic commands ###
