"""Add real journal_audit and parametres_securite tables

Revision ID: 5f35f9d08c80
Revises: b9ce75de0497
Create Date: 2026-08-11 13:34:45.788602

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f35f9d08c80'
down_revision: Union[str, Sequence[str], None] = 'b9ce75de0497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PARAMETRES_SECURITE = [
    {"id": "2fa", "label": "Authentification à deux facteurs — comptes sensibles", "actif": True, "ordre": 0},
    {"id": "verrouillage_tentatives", "label": "Verrouillage après 5 tentatives échouées", "actif": True, "ordre": 1},
    {"id": "expiration_session", "label": "Expiration de session après inactivité", "actif": True, "ordre": 2},
    {"id": "double_validation", "label": "Double validation — dépenses & transferts significatifs", "actif": True, "ordre": 3},
    {"id": "restriction_terminal", "label": "Restriction par terminal — comptes siège", "actif": False, "ordre": 4},
]

JOURNAL_AUDIT = [
    # boutique_id à None : ces entrées de démonstration référençaient des slugs fictifs
    # ("kankan", "madina"...) qui ne correspondent à aucune boutique réelle (les boutiques
    # ont des id UUID, seedés bien après cette migration) — violait la FK boutiques.id sur
    # tout moteur qui l'applique réellement (MySQL/MariaDB ; SQLite l'ignorait silencieusement).
    {"id": "aud-1", "horodatage": datetime(2026, 8, 8, 11, 2), "action": "Modification des droits — S. Bah passé en lecture seule", "auteur": "Sékou Condé", "boutique_id": None},
    {"id": "aud-2", "horodatage": datetime(2026, 8, 8, 10, 40), "action": "Validation transfert de stock #TR-208", "auteur": "Mamadouba Keita", "boutique_id": None},
    {"id": "aud-3", "horodatage": datetime(2026, 8, 8, 9, 15), "action": "Écart de caisse signalé (45 000 GNF)", "auteur": "Mariama Diallo", "boutique_id": None},
    {"id": "aud-4", "horodatage": datetime(2026, 8, 7, 18, 22), "action": "Dépense validée — loyer 1 200 000 GNF", "auteur": "Sékou Condé", "boutique_id": None},
    {"id": "aud-5", "horodatage": datetime(2026, 8, 7, 15, 3), "action": "Nouvelle commande fournisseur #FR-318", "auteur": "Ibrahima Sow", "boutique_id": None},
    {"id": "aud-6", "horodatage": datetime(2026, 8, 7, 9, 47), "action": "Connexion échouée x3 — compte verrouillé", "auteur": "Souleymane Bah", "boutique_id": None},
    {"id": "aud-7", "horodatage": datetime(2026, 8, 5, 16, 10), "action": "Correction d'inventaire — écart +4 unités", "auteur": "Alpha Camara", "boutique_id": None},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres_securite',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('auteur', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    parametres_table = sa.table(
        'parametres_securite',
        sa.column('id', sa.String),
        sa.column('label', sa.String),
        sa.column('actif', sa.Boolean),
        sa.column('ordre', sa.Integer),
    )
    op.bulk_insert(parametres_table, PARAMETRES_SECURITE)

    audit_table = sa.table(
        'journal_audit',
        sa.column('id', sa.String),
        sa.column('horodatage', sa.DateTime),
        sa.column('action', sa.String),
        sa.column('auteur', sa.String),
        sa.column('boutique_id', sa.String),
    )
    op.bulk_insert(audit_table, JOURNAL_AUDIT)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_audit')
    op.drop_table('parametres_securite')
    # ### end Alembic commands ###
