"""add livraisons depenses paiements tables

Revision ID: 605449af7e50
Revises: 9f6a0a8e328a
Create Date: 2026-08-10 02:52:25.794760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605449af7e50'
down_revision: Union[str, Sequence[str], None] = '9f6a0a8e328a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depenses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('categorie', sa.String(length=120), nullable=False),
    sa.Column('auteur', sa.String(length=160), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut_validation', sa.Enum('auto_validee', 'en_attente', 'validee_siege', name='statutvalidationdepense'), nullable=False),
    sa.Column('justificatif_disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements_clients',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_nom', sa.String(length=160), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('mode_paiement', sa.Enum('especes', 'mobile_money', 'a_la_livraison', 'credit_client', 'virement', 'lettre_change', name='modepaiement'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('encaisse', 'en_attente', 'paye', 'partiel', name='statutpaiement'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements_fournisseurs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('fournisseur_nom', sa.String(length=160), nullable=False),
    sa.Column('reference', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('mode_paiement', sa.Enum('especes', 'mobile_money', 'a_la_livraison', 'credit_client', 'virement', 'lettre_change', name='modepaiement'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('encaisse', 'en_attente', 'paye', 'partiel', name='statutpaiement'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livraisons',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('commande_id', sa.String(length=40), nullable=False),
    sa.Column('livreur', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('creneau', sa.String(length=80), nullable=False),
    sa.Column('statut', sa.Enum('preparee', 'en_cours', 'livree', 'echec', name='statutlivraison'), nullable=False),
    sa.Column('preuve_disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livraisons')
    op.drop_table('paiements_fournisseurs')
    op.drop_table('paiements_clients')
    op.drop_table('depenses')
    # ### end Alembic commands ###
