"""add boutique geoloc, client zones, livraison preuve file, produit images

Revision ID: 8711ecc06d0b
Revises: 5b1bbe1965c4
Create Date: 2026-08-10 20:32:20.448115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8711ecc06d0b'
down_revision: Union[str, Sequence[str], None] = '5b1bbe1965c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produit_images',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boutiques', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('boutiques', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('quartier', sa.String(length=120), nullable=True))
    op.add_column('clients', sa.Column('commune', sa.String(length=120), nullable=True))
    op.add_column('clients', sa.Column('ville', sa.String(length=120), nullable=True))
    op.add_column('livraisons', sa.Column('preuve_url', sa.String(length=500), nullable=True))
    op.drop_column('livraisons', 'preuve_disponible')
    op.drop_column('produits', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('livraisons', sa.Column('preuve_disponible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('livraisons', 'preuve_url')
    op.drop_column('clients', 'ville')
    op.drop_column('clients', 'commune')
    op.drop_column('clients', 'quartier')
    op.drop_column('boutiques', 'longitude')
    op.drop_column('boutiques', 'latitude')
    op.drop_table('produit_images')
    # ### end Alembic commands ###
