"""Link paiements clients and fournisseurs to a caisse

Revision ID: 8b369f3cfa03
Revises: a45e0df35dda
Create Date: 2026-08-10 23:56:04.630141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b369f3cfa03'
down_revision: Union[str, Sequence[str], None] = 'a45e0df35dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements_clients', sa.Column('caisse_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'paiements_clients', 'caisses', ['caisse_id'], ['id'])
    op.add_column('paiements_fournisseurs', sa.Column('caisse_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'paiements_fournisseurs', 'caisses', ['caisse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paiements_fournisseurs', type_='foreignkey')
    op.drop_column('paiements_fournisseurs', 'caisse_id')
    op.drop_constraint(None, 'paiements_clients', type_='foreignkey')
    op.drop_column('paiements_clients', 'caisse_id')
    # ### end Alembic commands ###
