"""link caisse to depenses and remboursements, add promotions

Revision ID: 96f28269c142
Revises: b990ab79b3ba
Create Date: 2026-08-10 17:32:46.372294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96f28269c142'
down_revision: Union[str, Sequence[str], None] = 'b990ab79b3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=True),
    sa.Column('secteur', sa.Enum('habillement', 'alimentation_generale', 'electronique_electromenager', name='secteur'), nullable=True),
    sa.Column('origine', sa.Enum('ia', 'gerant', 'direction', name='originepromotion'), nullable=False),
    sa.Column('impact_estime', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.Enum('en_attente_validation', 'validee', 'active', 'terminee', name='statutpromotion'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('depenses', sa.Column('caisse_id', sa.String(length=40), nullable=True))
    op.add_column('depenses', sa.Column('justificatif_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'depenses', 'caisses', ['caisse_id'], ['id'])
    op.drop_column('depenses', 'justificatif_disponible')
    op.add_column('remboursements', sa.Column('caisse_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'remboursements', 'caisses', ['caisse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remboursements', type_='foreignkey')
    op.drop_column('remboursements', 'caisse_id')
    op.add_column('depenses', sa.Column('justificatif_disponible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'depenses', type_='foreignkey')
    op.drop_column('depenses', 'justificatif_url')
    op.drop_column('depenses', 'caisse_id')
    op.drop_table('promotions')
    # ### end Alembic commands ###
