"""add commande line items

Revision ID: 9f6a0a8e328a
Revises: ebed7cfd3b87
Create Date: 2026-08-10 02:17:48.525310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6a0a8e328a'
down_revision: Union[str, Sequence[str], None] = 'ebed7cfd3b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lignes_commandes_clients',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('commande_id', sa.String(length=40), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_commandes_fournisseurs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('commande_id', sa.String(length=40), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('quantite_recue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_fournisseurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lignes_commandes_fournisseurs')
    op.drop_table('lignes_commandes_clients')
    # ### end Alembic commands ###
