"""add date_creation to commandes clients and date_reception to commandes fournisseurs

Revision ID: a3a7d78c957f
Revises: 605449af7e50
Create Date: 2026-08-10 11:24:26.808251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a7d78c957f'
down_revision: Union[str, Sequence[str], None] = '605449af7e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commandes_clients', sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('commandes_fournisseurs', sa.Column('date_reception', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commandes_fournisseurs', 'date_reception')
    op.drop_column('commandes_clients', 'date_creation')
    # ### end Alembic commands ###
