"""Client can frequent multiple boutiques

Revision ID: a45e0df35dda
Revises: 8711ecc06d0b
Create Date: 2026-08-10 23:41:47.796191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a45e0df35dda'
down_revision: Union[str, Sequence[str], None] = '8711ecc06d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_boutiques',
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'boutique_id')
    )
    op.execute(
        "INSERT INTO client_boutiques (client_id, boutique_id) "
        "SELECT id, boutique_id FROM clients WHERE boutique_id IS NOT NULL"
    )
    op.drop_constraint(op.f('clients_ibfk_1'), 'clients', type_='foreignkey')
    op.drop_column('clients', 'boutique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('boutique_id', mysql.VARCHAR(length=40), nullable=True))
    op.execute(
        "UPDATE clients c SET boutique_id = ("
        "SELECT boutique_id FROM client_boutiques cb WHERE cb.client_id = c.id LIMIT 1"
        ")"
    )
    op.alter_column('clients', 'boutique_id', nullable=False)
    op.create_foreign_key(op.f('clients_ibfk_1'), 'clients', 'boutiques', ['boutique_id'], ['id'])
    op.drop_table('client_boutiques')
    # ### end Alembic commands ###
