"""add document_url to paiements fournisseurs

Revision ID: b990ab79b3ba
Revises: a3a7d78c957f
Create Date: 2026-08-10 13:55:47.025055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b990ab79b3ba'
down_revision: Union[str, Sequence[str], None] = 'a3a7d78c957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements_fournisseurs', sa.Column('document_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paiements_fournisseurs', 'document_url')
    # ### end Alembic commands ###
