"""Make matrice des droits editable via a permissions table

Revision ID: b9ce75de0497
Revises: 8b369f3cfa03
Create Date: 2026-08-11 01:33:00.108231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ce75de0497'
down_revision: Union[str, Sequence[str], None] = '8b369f3cfa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSIONS = [
    {"module_action": "Consulter le stock de sa boutique", "droits": {"vendeur": "complet", "caissier": "complet", "gerant": "complet", "responsable_achats": "complet", "administrateur": "complet"}},
    {"module_action": "Consulter le stock des autres boutiques", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "aucun", "responsable_achats": "complet", "administrateur": "complet"}},
    {"module_action": "Enregistrer une vente directe (caisse)", "droits": {"vendeur": "complet", "caissier": "complet", "gerant": "complet", "responsable_achats": "aucun", "administrateur": "complet"}},
    {"module_action": "Ouvrir / fermer une caisse", "droits": {"vendeur": "aucun", "caissier": "complet", "gerant": "complet", "responsable_achats": "aucun", "administrateur": "complet"}},
    {"module_action": "Créer une commande fournisseur", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "partiel", "responsable_achats": "partiel", "administrateur": "complet"}},
    {"module_action": "Initier un transfert de stock", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "partiel", "responsable_achats": "partiel", "administrateur": "complet"}},
    {"module_action": "Valider les dépenses au-delà d'un seuil", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "aucun", "responsable_achats": "complet", "administrateur": "complet"}},
    {"module_action": "Consulter le dashboard consolidé siège", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "aucun", "responsable_achats": "complet", "administrateur": "complet"}},
    {"module_action": "Gérer les droits utilisateurs", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "aucun", "responsable_achats": "aucun", "administrateur": "complet"}},
    {"module_action": "Créer / fermer une boutique", "droits": {"vendeur": "aucun", "caissier": "aucun", "gerant": "aucun", "responsable_achats": "aucun", "administrateur": "complet"}},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('module_action', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('vendeur', 'caissier', 'gerant', 'responsable_achats', 'administrateur', name='role'), nullable=False),
    sa.Column('droit', sa.Enum('complet', 'lecture_seule', 'partiel', 'aucun', name='droitacces'), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('module_action', 'role')
    )
    # ### end Alembic commands ###

    permissions_table = sa.table(
        'permissions',
        sa.column('module_action', sa.String),
        sa.column('role', sa.String),
        sa.column('droit', sa.String),
        sa.column('ordre', sa.Integer),
    )
    rows = [
        {"module_action": ligne["module_action"], "role": role, "droit": droit, "ordre": ordre}
        for ordre, ligne in enumerate(PERMISSIONS)
        for role, droit in ligne["droits"].items()
    ]
    op.bulk_insert(permissions_table, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
