"""initial schema: boutiques, utilisateurs, produits

Revision ID: e3c2d65baea1
Revises: 
Create Date: 2026-08-09 20:12:19.012391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c2d65baea1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boutiques',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('quartier', sa.String(length=120), nullable=False),
    sa.Column('commune', sa.String(length=120), nullable=False),
    sa.Column('ville', sa.String(length=120), nullable=False),
    sa.Column('horaires', sa.String(length=120), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('statut', sa.Enum('active', 'fermee', 'en_creation', name='statutboutique'), nullable=False),
    sa.Column('telephone', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('secteur', sa.Enum('habillement', 'alimentation_generale', 'electronique_electromenager', name='secteur'), nullable=False),
    sa.Column('categorie', sa.String(length=120), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=40), nullable=False),
    sa.Column('code_barres', sa.String(length=40), nullable=False),
    sa.Column('date_peremption', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_barres')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=40), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('vendeur', 'caissier', 'gerant', 'responsable_achats', 'administrateur', name='role'), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_contact'), 'utilisateurs', ['contact'], unique=True)
    op.create_table('boutique_secteurs',
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('secteur', sa.Enum('habillement', 'alimentation_generale', 'electronique_electromenager', name='secteur'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('boutique_id', 'secteur')
    )
    op.create_table('utilisateur_boutiques',
    sa.Column('utilisateur_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utilisateur_id', 'boutique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur_boutiques')
    op.drop_table('boutique_secteurs')
    op.drop_index(op.f('ix_utilisateurs_contact'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('produits')
    op.drop_table('boutiques')
    # ### end Alembic commands ###
