"""add produits image, fournisseurs, clients, stock, caisse, commandes, dettes, transferts tables

Revision ID: ebed7cfd3b87
Revises: f91fc0da70f2
Create Date: 2026-08-10 00:19:54.790681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebed7cfd3b87'
down_revision: Union[str, Sequence[str], None] = 'f91fc0da70f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fournisseurs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('secteur', sa.Enum('habillement', 'alimentation_generale', 'electronique_electromenager', name='secteur'), nullable=False),
    sa.Column('conditions_paiement', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caisses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('statut', sa.Enum('ouverte', 'fermee', 'ecart_signale', name='statutcaisse'), nullable=False),
    sa.Column('fond_initial', sa.Float(), nullable=False),
    sa.Column('solde_theorique', sa.Float(), nullable=False),
    sa.Column('solde_reel', sa.Float(), nullable=False),
    sa.Column('operateur', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=60), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('segment', sa.Enum('nouveau', 'regulier', 'fidele', 'a_risque', name='segmentclient'), nullable=False),
    sa.Column('credit_autorise', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes_clients',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_nom', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('canal', sa.Enum('web', 'mobile_client', 'boutique', name='canalcommande'), nullable=False),
    sa.Column('mode_paiement', sa.Enum('especes', 'mobile_money', 'a_la_livraison', 'credit_client', 'virement', 'lettre_change', name='modepaiement'), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('en_attente', 'confirmee', 'en_preparation', 'en_livraison', 'livree', 'annulee', name='statutcommandeclient'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandes_fournisseurs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('fournisseur_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('date_attendue', sa.Date(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'validee', 'envoyee', 'receptionnee_partielle', 'receptionnee', 'cloturee', name='statutcommandefournisseur'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dettes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tiers_type', sa.Enum('client', 'fournisseur', name='tierstype'), nullable=False),
    sa.Column('tiers_nom', sa.String(length=160), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('montant_initial', sa.Float(), nullable=False),
    sa.Column('solde_restant', sa.Float(), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('en_cours', 'en_retard', 'soldee', name='statutdette'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecarts_inventaire',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('theorique', sa.Integer(), nullable=False),
    sa.Column('reel', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('conforme', 'a_investiguer', 'corrige', name='statutecartinventaire'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements_stock',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('motif', sa.Enum('vente_caisse', 'commande_client', 'achat_reception_fournisseur', 'transfert_entrant', 'transfert_sortant', 'retour_client', 'casse_perte', 'peremption', 'correction_inventaire', 'don_echantillon', 'autre', name='motifmouvementstock'), nullable=False),
    sa.Column('operateur', sa.String(length=120), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_boutiques',
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('quantite_disponible', sa.Integer(), nullable=False),
    sa.Column('quantite_reservee', sa.Integer(), nullable=False),
    sa.Column('seuil_alerte', sa.Integer(), nullable=False),
    sa.Column('derniere_mouvement', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('boutique_id', 'produit_id')
    )
    op.create_table('transferts_stock',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('produit_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_source_id', sa.String(length=40), nullable=False),
    sa.Column('boutique_destination_id', sa.String(length=40), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('demandeur', sa.String(length=160), nullable=False),
    sa.Column('statut', sa.Enum('demande', 'valide', 'en_transit', 'recu', name='statuttransfert'), nullable=False),
    sa.ForeignKeyConstraint(['boutique_destination_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['boutique_source_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements_caisse',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('boutique_id', sa.String(length=40), nullable=False),
    sa.Column('caisse_id', sa.String(length=40), nullable=False),
    sa.Column('caisse_libelle', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('encaissement', 'decaissement', name='typemouvementcaisse'), nullable=False),
    sa.Column('motif', sa.String(length=160), nullable=False),
    sa.Column('operateur', sa.String(length=120), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutiques.id'], ),
    sa.ForeignKeyConstraint(['caisse_id'], ['caisses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remboursements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('dette_id', sa.String(length=40), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('mode_paiement', sa.Enum('especes', 'mobile_money', 'a_la_livraison', 'credit_client', 'virement', 'lettre_change', name='modepaiement'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('operateur', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['dette_id'], ['dettes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('produits', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produits', 'image_url')
    op.drop_table('remboursements')
    op.drop_table('mouvements_caisse')
    op.drop_table('transferts_stock')
    op.drop_table('stock_boutiques')
    op.drop_table('mouvements_stock')
    op.drop_table('ecarts_inventaire')
    op.drop_table('dettes')
    op.drop_table('commandes_fournisseurs')
    op.drop_table('commandes_clients')
    op.drop_table('clients')
    op.drop_table('caisses')
    op.drop_table('fournisseurs')
    # ### end Alembic commands ###
