"""add referentiels table

Revision ID: f91fc0da70f2
Revises: e3c2d65baea1
Create Date: 2026-08-09 22:33:24.913518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91fc0da70f2'
down_revision: Union[str, Sequence[str], None] = 'e3c2d65baea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referentiels',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('categorie', sa.String(length=60), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referentiels_categorie'), 'referentiels', ['categorie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referentiels_categorie'), table_name='referentiels')
    op.drop_table('referentiels')
    # ### end Alembic commands ###
